import { EventModel } from 'app/shared/models/event.model';

export class CheckInModel {
    id?: number;
    job_id: number;
    project?: number;
    memorial?: number;
    budget?: number;
    approval: boolean;
    approval_employee_id: number;
    approval_date: string;
    accept_client: boolean;
    accept_client_date: string;
    accept_proposal: boolean;
    accept_proposal_employee_id: number;
    accept_proposal_date: string;
    accept_production: boolean;
    accept_production_employee_id: number;
    accept_production_date: string;
    board_approval: boolean;
    board_approval_employee_id: number;
    board_approval_date: string;
    financial_acceptance: boolean;
    financial_acceptance_employee_id: number;
    financial_acceptance_date: string;
    area?: number;
    config?: string;
    location?: string;
    pavilion?: string;
    organization_id?: number;
    organization_login?: string;
    organization_password?: string;
    organization_changed_by?: number;
    organization_changed_in?: string | Date;
    promoter_name?: string;
    promoter_login?: string;
    promoter_password?: string;
    promoter_changed_by?: number;
    promoter_changed_in?: string | Date;
    event_id?: EventModel;
    event_changed_by?: number;
    event_changed_in?: string | Date;
    approval_note?: string = null;
    contact_obs?: string = null;
    billing_client_id?: number;
    costumer_service_employee: null;
    costumer_service_comission: null;
    costumer_service_employee2: null;
    costumer_service_comission2: null;
    creation_employee: null;
    creation_comission: null;
    creation_employee2: null;
    creation_comission2: null;
    production_manager_employee: null;
    production_manager_comission: null;
    production_manager_employee2: null;
    production_manager_comission2: null;
    budget_employee: null;
    budget_comission: null;
    budget_employee2: null;
    budget_comission2: null;
    detailing_employee: null;
    detailing_comission: null;
    detailing_employee2: null;
    detailing_comission2: null;
    production_employee: null;
    production_comission: null;
    production_employee2: null;
    production_comission2: null;
    billing_obs: string;
    bv_customer_service: number;
    billing_amount_obs?: string;
    extras_obs?: string;

    constructor() {
        this.approval_note = null;
        this.contact_obs = null;
        this.billing_obs = null;
        this.billing_amount_obs = null;
        this.extras_obs = null;
    }
}
